In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [16]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(c)
print('vectorized version:' + str(1000*(toc-tic)) + 'ms')

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print('for loop:' + str(1000*(toc-tic)) + 'ms')

250074.05889947683
vectorized version:0.3609657287597656ms
250074.05889948556
for loop:328.7498950958252ms


In [24]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [27]:
cal = A.sum(axis=0)
cal.reshape(1,4)

array([[ 59. , 239. , 155.4,  76.9]])

In [26]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


# Python-Numpy Vectors

In [28]:
a = np.random.randn(5)
print(a)

[-0.29539043  1.12661487  0.49802404  0.05968587 -0.35250805]


In [29]:
# rank 1 array

print(a.shape)

(5,)


In [30]:
# ends up looking the same as vector a

a.T

array([-0.29539043,  1.12661487,  0.49802404,  0.05968587, -0.35250805])

In [31]:
print(np.dot(a, a.T))

1.732368851810405


In [32]:
b = np.random.randn(5, 1)
print(b)

[[-0.20590861]
 [-0.00629713]
 [ 3.04170264]
 [-2.65131993]
 [ 0.40270882]]


In [33]:
b.T

array([[-0.20590861, -0.00629713,  3.04170264, -2.65131993,  0.40270882]])

In [34]:
print(np.dot(b, b.T))

[[ 4.23983542e-02  1.29663406e-03 -6.26312751e-01  5.45929593e-01
  -8.29212125e-02]
 [ 1.29663406e-03  3.96538948e-05 -1.91540086e-02  1.66957165e-02
  -2.53591136e-03]
 [-6.26312751e-01 -1.91540086e-02  9.25195492e+00 -8.06452683e+00
   1.22492049e+00]
 [ 5.45929593e-01  1.66957165e-02 -8.06452683e+00  7.02949739e+00
  -1.06770993e+00]
 [-8.29212125e-02 -2.53591136e-03  1.22492049e+00 -1.06770993e+00
   1.62174396e-01]]


In [39]:
a = a.reshape(5, 1)
a

array([[-0.29539043],
       [ 1.12661487],
       [ 0.49802404],
       [ 0.05968587],
       [-0.35250805]])

In [45]:
a = np.random.randn(1,3)
b = np.random.randn(3,3)
c = a*b
c

array([[ 0.09545853, -0.56122935,  0.50919807],
       [-0.36320025,  0.04506138, -1.13936322],
       [ 0.07040785,  0.33506857, -0.40645644]])

In [47]:
a = np.array([[2, 1], [1, 3]])
np.dot(a, a)

array([[ 5,  5],
       [ 5, 10]])

In [52]:
a = np.array([[0, 0, 0],
            [1, 1, 1],
            [2, 2, 2],
             [3, 3, 3]])
b = np.array([[0], [1], [2], [3]])
c = a + b
c

array([[0, 0, 0],
       [2, 2, 2],
       [4, 4, 4],
       [6, 6, 6]])

In [2]:
import numpy as np

A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True) 
B.shape

(4, 1)